--- 
title: "5293-Final-project"
author: "Xinyu Zhang & Dexin Sun"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

Education has always been a top priority for people in the United States. Over the past few years, the U.S. has dominated the globe in being the most popular university destination for students from all over the world. And New York is not only a cosmopolitan city full of opportunity and charm, it is also home to some of the world’s most prestigious universities.
What about high schools in New York? 

We want to know what high school education in New York is like. What is the geographical distribution of high schools in New York? Are these distributions evenly? And we all know that high school studies are very important to get into a good university, and there are many websites that rank these high schools. Is it true that the schools that are ranked at the bottom of the list are very different from the top one? Also, people have experienced the epidemic for the past two years, what kind of impact has the epidemic had on high school education? Has it influence the attendance of students? 

We hope to analyze some datasets to better understand New York high school education and to answer the above questions.